import type {
  Account,
  BrokerProfile,
  CallRecord,
  CallStage,
  ObjectionCode,
  Turn,
} from "./types";

const t = (
  speaker: Turn["speaker"],
  text: string,
  atMs: number,
): Turn => ({ speaker, text, atMs });

export const BROKERS: BrokerProfile[] = [
  {
    id: "jordan",
    name: "Jordan Hale",
    strength: "Persistence at the gate",
    weakness: "Talks too long during introductions",
    bestOpener: "Renewal-focused",
    commonMistake: "Over-explaining after a soft yes",
    talkListenTarget: 0.45,
  },
  {
    id: "priya",
    name: "Priya Shah",
    strength: "Discovery questions",
    weakness: "Sometimes slow to ask for the meeting",
    bestOpener: "Who-handles-renewal",
    commonMistake: "Leaving without a time",
    talkListenTarget: 0.4,
  },
  {
    id: "marcus",
    name: "Marcus Lee",
    strength: "Short asks, high meeting rate",
    weakness: "Can skip rapport on first DM touch",
    bestOpener: "Renewal-focused",
    commonMistake: "Jumping to close before one discovery question",
    talkListenTarget: 0.35,
  },
];

export const ACCOUNTS: Account[] = [
  {
    id: "acme",
    name: "Acme Manufacturing",
    industry: "Manufacturing",
    decisionMaker: "Sarah Chen",
    decisionMakerTitle: "COO",
    renewalMonth: "October",
    lastCallAt: "2026-05-14",
    lastObjection: "happy_with_broker",
    lastApproach: "Generic savings pitch",
    lastOutcome: "no_meeting",
    notes: "Do not repeat the savings pitch. Service-gap question only.",
    doNotRepeat: ["Generic savings pitch", "We can beat your rate"],
  },
  {
    id: "harbor",
    name: "Harbor Logistics",
    industry: "Logistics",
    decisionMaker: "Luis Ortega",
    decisionMakerTitle: "Owner",
    renewalMonth: "March",
    lastCallAt: "2026-08-02",
    lastObjection: "send_email",
    lastApproach: "Asked for email to info@",
    lastOutcome: "email_promised",
    notes: "Gatekeeper previously routed to info@. Push for Luis.",
    doNotRepeat: ["Sending a brochure to info@"],
  },
  {
    id: "northwind",
    name: "Northwind Dental Group",
    industry: "Healthcare",
    decisionMaker: "Dr. Anita Kapoor",
    decisionMakerTitle: "Managing Partner",
    renewalMonth: "January",
    lastCallAt: null,
    lastObjection: null,
    lastApproach: null,
    lastOutcome: null,
    notes: "New account. Renewal month unknown until confirmed on a call.",
    doNotRepeat: [],
  },
  {
    id: "pike",
    name: "Pike & Co. Construction",
    industry: "Construction",
    decisionMaker: "Evan Pike",
    decisionMakerTitle: "President",
    renewalMonth: "June",
    lastCallAt: "2026-06-20",
    lastObjection: "all_set",
    lastApproach: "We're all set brush-off",
    lastOutcome: "gatekeeper_block",
    notes: "Never reached Evan. Try naming him.",
    doNotRepeat: [],
  },
  {
    id: "lumen",
    name: "Lumen Foods",
    industry: "Food production",
    decisionMaker: "Maya Brooks",
    decisionMakerTitle: "CFO",
    renewalMonth: "November",
    lastCallAt: "2026-07-09",
    lastObjection: "no_time",
    lastApproach: "Caught Maya between meetings",
    lastOutcome: "callback",
    notes: "Maya asked to try Thursday mornings.",
    doNotRepeat: ["Long product dump"],
  },
  {
    id: "redoak",
    name: "Red Oak Warehousing",
    industry: "Logistics",
    decisionMaker: "Tom Nguyen",
    decisionMakerTitle: "VP Operations",
    renewalMonth: "September",
    lastCallAt: "2026-04-03",
    lastObjection: "already_renewed",
    lastApproach: "Asked for next-term date",
    lastOutcome: "callback",
    notes: "They renewed in April. Next conversation is for next cycle only.",
    doNotRepeat: ["Quote request on this term"],
  },
];

function call(
  id: string,
  accountId: string,
  brokerId: string,
  startedAt: string,
  openerVariant: CallRecord["openerVariant"],
  turns: Turn[],
  stageReached: CallStage,
  outcome: CallRecord["outcome"],
  objections: ObjectionCode[],
): CallRecord {
  return {
    id,
    accountId,
    brokerId,
    startedAt,
    endedAt: startedAt,
    openerVariant,
    turns,
    stageReached,
    outcome,
    objections,
    debrief: null,
    synthetic: true,
  };
}

export const CALLS: CallRecord[] = [
  call(
    "c1",
    "acme",
    "jordan",
    "2026-05-14T14:02:00Z",
    "A",
    [
      t("broker", "Hi, I'm calling from ABC Insurance — we help manufacturers save on their programs.", 0),
      t("gatekeeper", "What is this regarding?", 4000),
      t("broker", "We're an insurance brokerage. We shop multiple carriers and usually find savings.", 8000),
      t("gatekeeper", "Just send an email to info@.", 14000),
      t("broker", "Sure, I'll send something over. Thanks.", 18000),
    ],
    "gatekeeper",
    "email_promised",
    ["what_regarding", "send_email"],
  ),
  call(
    "c2",
    "acme",
    "priya",
    "2026-08-21T15:10:00Z",
    "B",
    [
      t("broker", "Hi, this is Priya — I'm calling because Acme's insurance renewal typically hits in October. Is Sarah Chen still the person on that?", 0),
      t("gatekeeper", "Who are you trying to reach?", 5000),
      t("broker", "Sarah Chen, on the commercial program renewal.", 8000),
      t("decision_maker", "This is Sarah. We're happy with our current broker.", 12000),
      t("broker", "If you could change one thing about that relationship, what would it be?", 16000),
      t("decision_maker", "They've been slow after claims. Thursday might work for a short call.", 20000),
    ],
    "close",
    "meeting_booked",
    ["who_trying_to_reach", "happy_with_broker"],
  ),
  call(
    "c3",
    "harbor",
    "jordan",
    "2026-08-02T16:00:00Z",
    "A",
    [
      t("broker", "Hi, Jordan at ABC Insurance, we help logistics companies lower premiums.", 0),
      t("gatekeeper", "We're all set. Send an email.", 4000),
      t("broker", "Okay, I'll email info@.", 7000),
    ],
    "gatekeeper",
    "gatekeeper_block",
    ["all_set", "send_email"],
  ),
  call(
    "c4",
    "harbor",
    "marcus",
    "2026-08-28T11:20:00Z",
    "B",
    [
      t("broker", "I'm calling because Harbor's renewal is in March — is Luis Ortega the right person?", 0),
      t("gatekeeper", "What is this regarding?", 4000),
      t("broker", "Luis's insurance renewal, not a pitch for info@.", 7000),
      t("decision_maker", "This is Luis. I don't have time.", 11000),
      t("broker", "Understood — Tuesday at 10 or Thursday at 2 for twelve minutes?", 14000),
      t("decision_maker", "Thursday might work.", 18000),
    ],
    "close",
    "meeting_booked",
    ["what_regarding", "no_time"],
  ),
  call(
    "c5",
    "pike",
    "jordan",
    "2026-06-20T13:00:00Z",
    "A",
    [
      t("broker", "Hi I'm calling from ABC, um, we basically shop insurance and, you know, save people money.", 0),
      t("gatekeeper", "We're all set.", 6000),
      t("broker", "Got it, thanks.", 8000),
    ],
    "gatekeeper",
    "gatekeeper_block",
    ["all_set"],
  ),
  call(
    "c6",
    "pike",
    "marcus",
    "2026-08-12T10:15:00Z",
    "B",
    [
      t("broker", "Calling for Evan Pike on the June insurance renewal — is he available?", 0),
      t("gatekeeper", "Who are you trying to reach?", 3000),
      t("broker", "Evan Pike.", 5000),
      t("decision_maker", "Evan speaking. Not interested.", 9000),
      t("broker", "Fair. When does the program renew so I don't call at a bad time?", 12000),
      t("decision_maker", "June. Call me in April.", 16000),
    ],
    "discovery",
    "callback",
    ["who_trying_to_reach", "not_interested"],
  ),
  call(
    "c7",
    "lumen",
    "priya",
    "2026-07-09T14:40:00Z",
    "B",
    [
      t("broker", "Priya here — Maya Brooks on the November renewal?", 0),
      t("decision_maker", "This is Maya. Caught me at a bad time.", 4000),
      t("broker", "I'll try Thursday morning. Is that still best?", 7000),
      t("decision_maker", "Yes, Thursday mornings.", 10000),
    ],
    "discovery",
    "callback",
    ["no_time"],
  ),
  call(
    "c8",
    "lumen",
    "priya",
    "2026-08-07T14:05:00Z",
    "B",
    [
      t("broker", "Maya — you asked me to try Thursday mornings. Twelve minutes on the November program?", 0),
      t("decision_maker", "Our renewal is November. Service has been messy. I could do Friday.", 5000),
    ],
    "close",
    "meeting_booked",
    [],
  ),
  call(
    "c9",
    "northwind",
    "jordan",
    "2026-08-18T09:30:00Z",
    "A",
    [
      t("broker", "Hi I'm with ABC Insurance and we, um, work with dental groups to, you know, find better rates and basically we work with a lot of carriers.", 0),
      t("gatekeeper", "Send some information.", 8000),
      t("broker", "I'll send a packet.", 10000),
    ],
    "gatekeeper",
    "email_promised",
    ["send_info"],
  ),
  call(
    "c10",
    "northwind",
    "marcus",
    "2026-08-25T09:50:00Z",
    "B",
    [
      t("broker", "I'm looking for whoever handles Northwind's insurance renewal — usually the managing partner.", 0),
      t("gatekeeper", "What is this regarding?", 4000),
      t("broker", "Dr. Kapoor's program renewal timing, not a quote.", 7000),
      t("decision_maker", "This is Anita. We might be open to a conversation. What would that look like?", 12000),
      t("broker", "Twelve minutes. Thursday 10 or Friday 2.", 16000),
      t("decision_maker", "Friday might work.", 19000),
    ],
    "close",
    "meeting_booked",
    ["what_regarding"],
  ),
  call(
    "c11",
    "redoak",
    "priya",
    "2026-04-03T16:22:00Z",
    "B",
    [
      t("broker", "Calling because Red Oak often renews in the fall — is Tom Nguyen the person?", 0),
      t("decision_maker", "We just renewed.", 5000),
      t("broker", "When does this new term end? I won't pitch today.", 8000),
      t("decision_maker", "Next September. Try me next summer.", 12000),
    ],
    "discovery",
    "callback",
    ["already_renewed"],
  ),
  call(
    "c12",
    "harbor",
    "priya",
    "2026-07-11T13:12:00Z",
    "A",
    [
      t("broker", "Hi we help companies save on insurance.", 0),
      t("gatekeeper", "We're all set.", 3000),
      t("broker", "If I could just explain our process and the carriers we use and how the marketing works...", 5000),
    ],
    "gatekeeper",
    "no_meeting",
    ["all_set"],
  ),
];

export const SCENARIOS = [
  {
    id: "acme-live",
    title: "Acme · gatekeeper → Sarah",
    subtitle: "Account memory: she said “happy with broker” in May",
    accountId: "acme",
    brokerId: "priya",
    turns: CALLS.find((c) => c.id === "c2")!.turns,
  },
  {
    id: "harbor-email",
    title: "Harbor · “send an email”",
    subtitle: "Classic gatekeeper brush-off",
    accountId: "harbor",
    brokerId: "marcus",
    turns: [
      t("broker", "Hi, I'm calling from ABC Insurance about Harbor's commercial program.", 0),
      t("gatekeeper", "What is this regarding?", 4000),
      t("broker", "We're an insurance brokerage — we work with logistics companies.", 8000),
      t("gatekeeper", "Just send an email to info@.", 13000),
      t("decision_maker", "This is Luis. I don't have time.", 22000),
      t("decision_maker", "Thursday might work.", 30000),
    ],
  },
  {
    id: "jordan-ramble",
    title: "Jordan · rambling intro",
    subtitle: "Coach should tell him to stop talking",
    accountId: "northwind",
    brokerId: "jordan",
    turns: CALLS.find((c) => c.id === "c9")!.turns,
  },
  {
    id: "pike-allset",
    title: "Pike · “we're all set”",
    subtitle: "Reflex objection vs. genuine",
    accountId: "pike",
    brokerId: "marcus",
    turns: CALLS.find((c) => c.id === "c6")!.turns,
  },
];
